# Generated by Django 6.1 on 2026-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('processing_mode', models.CharField(choices=[('viral', 'Viral Mode'), ('normal', 'Normal Mode'), ('full', 'Full Video Mode')], default='viral', max_length=20)),
                ('output_format', models.CharField(choices=[('vertical', 'Vertical 1080x1920'), ('horizontal', 'Horizontal 1920x1080')], default='vertical', max_length=20)),
                ('duration', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
