# Generated by Django 6.1 on 2026-09-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0002_youtubecredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('token_json', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='youtubecredential',
            name='channel_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
