# Generated by Django 6.1 on 2026-09-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0003_instagramcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='selected_instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='repurposer.instagramcredential'),
        ),
        migrations.AddField(
            model_name='video',
            name='selected_youtube_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='repurposer.youtubecredential'),
        ),
    ]
