# Generated by Django 6.1 on 2026-09-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0004_video_selected_instagram_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200)),
                ('page_id', models.CharField(max_length=200, unique=True)),
                ('token_json', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='processing_mode',
            field=models.CharField(choices=[('viral', 'Viral Clip'), ('normal', 'Normal Cut Sequence')], default='viral', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='selected_facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='repurposer.facebookcredential'),
        ),
    ]
