# Generated by Django 6.1 on 2026-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0006_scheduledpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_stage',
            field=models.CharField(default='Waiting', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='workflow_mode',
            field=models.CharField(choices=[('auto', 'Auto System'), ('manual', 'Manual System')], default='auto', max_length=20),
        ),
    ]
