# Generated by Django 6.1 on 2026-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0007_video_processing_progress_video_processing_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('user_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('token_json', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
