# Generated by Django 6.1 on 2026-09-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0008_xcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='x_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_posts', to='repurposer.xcredential'),
        ),
        migrations.AddField(
            model_name='video',
            name='selected_x_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='repurposer.xcredential'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X')], max_length=20),
        ),
    ]
