# Generated by Django 6.1 on 2026-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repurposer', '0010_facebookcredential_user_instagramcredential_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/'),
        ),
    ]
