"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(BASE_DIR / '.env')
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
YOUTUBE_API_KEY = os.environ.get(
    "YOUTUBE_API_KEY",
    ""
)


# ============================================================
# SECURITY
# ============================================================
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-s)axf##a)*&$-ml4fq-^l5h0c7@j9)i*e8f=pdawl_cd*2-v3b")
DEBUG = True


# ============================================================
# APPLICATION / HOST SETTINGS
# ============================================================
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    "ai-video-repurposer.onrender.com"
]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'repurposer',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    # Current Quick Tunnel
    'https://charter-northeast-groove-prevent.trycloudflare.com',
    'https://illustrations-find-prefer-commercial.trycloudflare.com',
    'https://der-speaks-enjoy-feedback.trycloudflare.com',
    'https://specs-joined-kodak-compute.trycloudflare.com',
    'https://gps-acting-physical-unsubscribe.trycloudflare.com',
    'https://maryland-liverpool-routes-spreading.trycloudflare.com',
    # Previous Quick Tunnel hosts
    'https://monica-policies-wales-citizenship.trycloudflare.com',
    'https://drew-pilot-catch-expectations.trycloudflare.com',
    'https://conversation-interactive-theater-preferences.trycloudflare.com',
    'https://brother-lift-objects-greene.trycloudflare.com',
    'https://various-reflects-discover-tiles.trycloudflare.com',
    'https://julie-related-horizontal-never.trycloudflare.com',
    'https://midi-consultants-curve-pubs.trycloudflare.com',    
    'https://heather-exciting-invisible-spyware.trycloudflare.com',
    'https://frankfurt-cheaper-hospital-input.trycloudflare.com',
    'https://tips-purposes-motherboard-salvation.trycloudflare.com'
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# EMAIL
# ============================================================
# Gmail SMTP configuration.
#
# Keep the real Gmail address and Gmail App Password in .env:
#
# EMAIL_HOST_USER=your-real-gmail@gmail.com
# EMAIL_HOST_PASSWORD=your-16-character-app-password
#
# Never put the Gmail password directly in this file.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get(
    'EMAIL_HOST',
    'smtp.gmail.com',
)
EMAIL_PORT = int(
    os.environ.get(
        'EMAIL_PORT',
        '587',
    )
)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get(
    'EMAIL_HOST_USER',
    '',
)
EMAIL_HOST_PASSWORD = os.environ.get(
    'EMAIL_HOST_PASSWORD',
    '',
)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER,
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = 20


# ============================================================
# META APP SETTINGS
# ============================================================

META_APP_ID = os.environ.get(
    'META_APP_ID',
    ''
)

META_APP_SECRET = os.environ.get(
    'META_APP_SECRET',
    ''
)


# ============================================================
# INSTAGRAM APP CONFIGURATION
# ============================================================

INSTAGRAM_APP_ID = os.environ.get(
    'INSTAGRAM_APP_ID',
    '37792592507055727'
)

INSTAGRAM_APP_SECRET = os.environ.get(
    'INSTAGRAM_APP_SECRET',
    ''
)


# ============================================================
# INSTAGRAM OAUTH REDIRECT URI
# ============================================================

INSTAGRAM_REDIRECT_URI = (
    'https://tips-purposes-motherboard-salvation.trycloudflare.com'
    '/instagram/callback/'
)


# ============================================================
# FACEBOOK LOGIN FOR BUSINESS
# ============================================================

FACEBOOK_LOGIN_CONFIG_ID = (
    '2549317355493004'
)


# ============================================================
# FACEBOOK OAUTH REDIRECT URI
# ============================================================

FACEBOOK_REDIRECT_URI = (
    'https://tips-purposes-motherboard-salvation.trycloudflare.com'
    '/facebook/callback/'
)


# ============================================================
# X OAUTH REDIRECT URI
# ============================================================
X_CLIENT_ID = os.environ.get(
    'X_CLIENT_ID',
    ''
)

X_CLIENT_SECRET = os.environ.get(
    'X_CLIENT_SECRET',
    ''
)

X_REDIRECT_URI = (
    'https://tips-purposes-motherboard-salvation.trycloudflare.com/'
    'x/callback/'
)


# ============================================================
# PUBLIC URL
# ============================================================

PUBLIC_BASE_URL = (
     'https://tips-purposes-motherboard-salvation.trycloudflare.com'
)


# Authentication
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"