"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse, unquote
import os

from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(BASE_DIR / ".env")


GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY",
    ""
)


YOUTUBE_API_KEY = os.environ.get(
    "YOUTUBE_API_KEY",
    ""
)


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY environment variable is required."
    )


DEBUG = os.environ.get(
    "DEBUG",
    "False"
).strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)


# ============================================================
# APPLICATION / HOST SETTINGS
# ============================================================

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "ai-video-repurposer.onrender.com",
]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "repurposer",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
]


# ============================================================
# CSRF TRUSTED ORIGINS
# ============================================================

CSRF_TRUSTED_ORIGINS = [
    "https://ai-video-repurposer.onrender.com",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()


if DATABASE_URL:
    parsed_database_url = urlparse(DATABASE_URL)

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (
                parsed_database_url.path.lstrip("/")
            ),
            "USER": (
                unquote(
                    parsed_database_url.username or ""
                )
            ),
            "PASSWORD": (
                unquote(
                    parsed_database_url.password or ""
                )
            ),
            "HOST": (
                parsed_database_url.hostname or ""
            ),
            "PORT": (
                parsed_database_url.port or 5432
            ),
        }
    }

else:
    # Local development continues using SQLite.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)


EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "smtp.gmail.com",
)


EMAIL_PORT = int(
    os.environ.get(
        "EMAIL_PORT",
        "587",
    )
)


EMAIL_USE_TLS = True


EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "",
)


EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    "",
)


DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)


SERVER_EMAIL = DEFAULT_FROM_EMAIL


EMAIL_TIMEOUT = 20


# ============================================================
# META APP SETTINGS
# ============================================================

META_APP_ID = os.environ.get(
    "META_APP_ID",
    ""
)


META_APP_SECRET = os.environ.get(
    "META_APP_SECRET",
    ""
)


# ============================================================
# INSTAGRAM APP CONFIGURATION
# ============================================================

INSTAGRAM_APP_ID = os.environ.get(
    "INSTAGRAM_APP_ID",
    "37792592507055727"
)


INSTAGRAM_APP_SECRET = os.environ.get(
    "INSTAGRAM_APP_SECRET",
    ""
)


# ============================================================
# INSTAGRAM OAUTH REDIRECT URI
# ============================================================

INSTAGRAM_REDIRECT_URI = (
    "https://ai-video-repurposer.onrender.com"
    "/instagram/callback/"
)


# ============================================================
# FACEBOOK LOGIN FOR BUSINESS
# ============================================================

FACEBOOK_LOGIN_CONFIG_ID = (
    "2549317355493004"
)


# ============================================================
# FACEBOOK OAUTH REDIRECT URI
# ============================================================

FACEBOOK_REDIRECT_URI = (
    "https://ai-video-repurposer.onrender.com"
    "/facebook/callback/"
)


# ============================================================
# X OAUTH SETTINGS
# ============================================================

X_CLIENT_ID = os.environ.get(
    "X_CLIENT_ID",
    ""
)


X_CLIENT_SECRET = os.environ.get(
    "X_CLIENT_SECRET",
    ""
)


X_REDIRECT_URI = (
    "https://ai-video-repurposer.onrender.com/"
    "x/callback/"
)


# ============================================================
# PUBLIC URL
# ============================================================

PUBLIC_BASE_URL = (
    "https://ai-video-repurposer.onrender.com"
)


# ============================================================
# AUTHENTICATION
# ============================================================

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/"


# ============================================================
# DJANGO CACHE / RATE LIMITING
# ============================================================

if os.environ.get("REDIS_URL"):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.environ.get("REDIS_URL"),
        }
    }

else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "ai-video-repurposer-local-cache",
        }
    }


# ============================================================
# CELERY
# ============================================================

CELERY_BROKER_URL = os.environ.get(
    "REDIS_URL",
    ""
)


CELERY_RESULT_BACKEND = os.environ.get(
    "REDIS_URL",
    ""
)


CELERY_ACCEPT_CONTENT = [
    "json",
]


CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE

CELERY_ENABLE_UTC = True


# ============================================================
# RATE LIMIT RESPONSE
# ============================================================

RATELIMIT_VIEW = "repurposer.views.ratelimited_error"